# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-16 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tridim_models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registereduser',
            name='has_badge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='uploadedmodel',
            name='has_badge',
            field=models.BooleanField(default=False),
        ),
    ]
