# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-16 19:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tridim_models', '0002_auto_20161016_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registereduser',
            name='has_badge',
        ),
        migrations.RemoveField(
            model_name='uploadedmodel',
            name='has_badge',
        ),
    ]
