# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-16 19:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tridim_models', '0002_auto_20161016_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(default='Description missing.')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BadgeType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('identifier', models.CharField(max_length=255, unique=True)),
                ('category', models.CharField(choices=[('local', 'local'), ('global', 'global')], max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='badge',
            name='badge_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='badges.BadgeType'),
        ),
        migrations.AddField(
            model_name='badge',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tridim_models.UploadedModel'),
        ),
        migrations.AddField(
            model_name='badge',
            name='proprietary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tridim_models.RegisteredUser'),
        ),
    ]
