# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-16 19:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0002_nb_views_badges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='badge_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='badges.BadgeType'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='tridim_models.UploadedModel'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='proprietary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='tridim_models.RegisteredUser'),
        ),
    ]
