# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-16 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tridim_models', '0003_auto_20161016_1950'),
        ('badges', '0003_auto_20161016_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgetype',
            name='description',
            field=models.TextField(default='Description missing.'),
        ),
        migrations.RemoveField(
            model_name='badge',
            name='description',
        ),
        migrations.AlterUniqueTogether(
            name='badge',
            unique_together=set([('badge_type', 'proprietary', 'model')]),
        ),
    ]
